name: shell command
on:
  - push

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"

      - name: versions
        run: |
          npm -v
          node -v
  run-shell-command-v2:
    runs-on: ubuntu-latest
    needs: 
      - run-shell-command
    steps:
      - name: echo another string
        run: echo "Bye World"

      - name: python scripts
        run: |
          import platform
          print('CPU Model : ',platform.processor())
          print('CPU ARCH x86 or x64 : ',platform.machine())
          print('OS : ', platform.platform())
        shell: python
