name: shell command
on:
  - push

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"

      - name: versions
        run: |
          npm -v
          node -v
  run-shell-command-v2:
    runs-on: ubuntu-latest
    steps:
      - name: echo another string
        run: echo "Bye World"
